<template>
  <div>
    <swiper class="swiper" :options="swiperOption">
      <swiper-slide class="text">
        <div class="centent">
          目标是录制1000集免费视频教程，从2016年开始录制，还在不断的努力，希望在程序生涯结束前，可以完成这个目标。
          我没有什么大的理想，只是觉的人到这个世界上，不能只为了自己活着，还应该尽自己所能去帮助别人。
          我没有什么大的能力，从上班开始就是写程序，最多算有点程序经验。
          很幸运，我赶上了最好的分享时代，所以我在这里分享所会的知识，希望帮助更多人学习成长。
          如果你支持我这样一个傻Ⅹ，请文章右侧加入知识星球和我一起学习（收费的哦）。
          本列表是倒叙排列，先录的视频在下面，上面的都是最新录制的视频。
          #1-React服务端渲染框架Next.js入门
          Next.js简介和创建项目(371)
          creact-next-app快速创建Next.js项目(370)
          Next.js的Page和Component的使用(369)
          路由-基础和基本跳转(368)
          路由-跳转时用query传递和接受参数(367)
          路由-六个钩子事件的讲解(366)
          在getInitialProps中用Axios获取远端数据(365)
          使用Style JSX编写页面的CSS样式(364)
          Lazy Loading实现模块懒加载(363)
          自定义Head 更加友好的SEO操作(362)
          Next.js框架下使用Ant Design UI(361)
          Next.js生产环境打包（完结）(360)
          #2-React Hooks免费视频教程
          React Hooks介绍和环境搭建(359)
          useState 的介绍和多状态声明(358)
          useEffect代替常用生命周期函数(357)
          useEffect 实现 componentWillUnmount生命周期函数(356)
          useContext 让父子组件传值更简单(355)
          useReducer介绍和简单使用(354)
          useReducer代替Redux小案例-1(353)
          useReducer代替Redux小案例-2(352)
          useMemo优化React Hooks程序性能(351)
          useRef获取DOM元素和保存变量(350)
          自定义Hooks函数获取窗口大小(349)
          #3-React Router免费视频教程
          React Router 安装和基础环境搭建(348)
          像制作普通网页一样使用ReactRouter(347)
          ReactRouter动态传值-1(346)
          ReactRouter动态传值-2(345)
          ReactRouter重定向-Redirect使用(344)
          实例-ReactRouter嵌套路由-1(343)
          实例-ReactRouter嵌套路由-2(342)
          实例-ReactRouter嵌套路由-3(341)
          后台动态获取路由进行配置(340)
          #4-Redux免费视频教程
          基础-认识redux和文章介绍(339)
          基础-Redux工作流程(338)
          Ant Design介绍和环境初始化(337)
          用Ant Design制作UI界面(336)
          创建Redux中的仓库-store和reducer(335)
          基础-Redux Dev Tools的安装(334)
          基础-通过Input体验Redux的流程(333)
          基础-Redux制作ToDoList列表(332)
          基础-用Redux实现ToDoList的删除功能(331)
          基础-工作中写Redux的小技巧-1(330)
          基础-工作中写Redux的小技巧-2(329)
          加餐-Redux填三个小坑(328)
          进阶-组件UI和业务逻辑的拆分方法(327)
          进阶-填坑和Redux中的无状态组件(326)
          进阶-Axios异步获取数据并和Redux结合(325)
          进阶-Redux-thunk中间件的安装和配置(324)
          进阶-Redux-thunk的使用方法(323)
          进阶-Redux-saga的安装和配置(322)
          进阶-用Redux-saga获取TodoList列表(321)
          进阶-React-Redux介绍和安装(320)
          进阶-React-redux中的Provider和connect(319)
          进阶-React-redux的数据修改(318)
          进阶-React-redux增加List数据(317)
          React-redux程序优化(完结)(316)
          #5-React（新版）基础免费视频教程
          React课程前言(315)
          React简介和Vue对比(314)
          React开发环境搭建(313)
          脚手架生成的项目目录介绍 (312)
          HelloWorld和组件的讲解 (311)
          React中JSX语法简介 (310)
          React实例-小姐姐服务菜单 (309)
          React实例-宝剑磨的好,理论不能少(308)
          React实例-老板我要加个钟(307)
          React实例-宝剑虽然好 老腰受不了(306)
          React进阶-JSX防踩坑的几个地方(305)
          React进阶-Simple React Snippets(304)
          React进阶-组件的拆分(303)
          React进阶-父子组件的传值(303)
          React进阶-单项数据流和其他(302)
          React高级-调试工具的安装及使用(301)
          React高级-PropTypes校验传递值(300)
          React高级-ref的使用方法(299)
          React高级-生命周期讲解-1(298)
          React高级-生命周期讲解-2(297)
          React高级-生命周期讲解-3(296)
          React高级-生命周期改善程序性能(295)
          React高级-axios数据请求(294)
          React高级-Axios请求EasyMock(293)
          React高级-用CSS3实现react动画(292)
          React高级-CSS3的keyframes动画(291)
          React高级-react-transition-group(290)
          React高级-多DOM动画制作和编写(289)
          #6-Flutter基础视频教程
          认识一下Flutter(288)
          Flutter开发环境搭建Windows版(287)
          Flutter开发环境搭建Mac版(286)
          安装AVD虚拟机 Flutter跑起来(285)
          VSCode下如何玩转Flutter(284)
          写一个HelloWorld程序(283)
          Text Widget 文本组件的使用(282)
          Container容器组件的使用1(281)
          Container容器组件的使用2(280)
          Image图片组件的使用(279)
          ListView 列表组件简介(278)
          ListView 横向列表的使用(277)
          ListView 动态列表的使用(276)
          GridView网格列表组件(275)
          Flutter-水平布局Row的使用(274)
          Flutter-垂直布局Column组件(273)
          Flutter-Stack层叠布局(272)
          Stack的Positioned属性(271)
          卡片组件布局(270)
          一般页面导航和返回(269)
          导航参数的传递和接收（1）(268)
          导航参数的传递和接收（2）(267)
          页面跳转并返回数据(266)
          静态资源和项目图片的处理(265)
          Flutter客户端打包(264)
          #7-Flutter 20课小实例练习
          底部导航栏制作-1(263)
          底部导航栏制作-2(262)
          不规则底部工具栏制作-1(261)
          不规则底部工具栏制作-2(260)
          酷炫的路由动画-1(259)
          酷炫的路由动画-2(258)
          毛玻璃效果制作(257)
          保持页面状态(256)
          保持页面状态-2(255)
          一个不简单的搜索条-1(254)
          一个不简单的搜索条-2(253)
          流式布局 模拟添加照片效果(252)
          展开闭合案例(251)
          展开闭合列表案例(250)
          贝塞尔曲线切割(249)
          波浪形式的贝塞尔曲线(248)
          打开应用的闪屏动画案例(247)
          右滑返回上一页案例(246)
          ToolTip控件实例(245)
          Draggable控件实例(244)
          #8-ES6免费视频教程（18集）
          ES6的开发环境搭建(243)
          新的声明方式(242)
          变量的解构赋值(241)
          扩展运算符和rest运算符(240)
          字符串模版(239)
          ES6数字操作(238)
          ES6中新增的数组知识（1）(237)
          ES6中新增的数组知识（2）(236)
          ES6中的箭头函数和扩展(235)
          ES6中的函数和数组补漏(234)
          ES6中对象(233)
          Symbol在对象中的作用(232)
          Set和WeakSet数据结构(231)
          map数据结构(230)
          用Proxy进行预处理(229)
          promise对象的使用(228)
          class类的使用(227)
          模块化操作(226)
          #9-前端必会的 Nginx免费教程 (共11集)
          初识Nginx和环境准备(225)
          Nginx的快速搭建(224)
          Nginx基本配置文件详讲(223)
          Nginx服务启动、停止、重启(222)
          自定义错误页和访问设置(221)
          Nginx访问权限详讲(220)
          Nginx设置虚拟主机(219)
          Nginx使用域名设置虚拟主机(218)
          Nginx反向代理的设置(217)
          Nginx适配PC或移动设备(216)
          Nginx的Gzip压缩配置(215)
          #10-TypeScript免费视频教程 ，Deno前置知识 (共15集)
          初识TypeScript(214)
          开发环境的安装(213)
          变量类型的那些事(212)
          TypeScript的函数(211)
          三种函数的定义方式(210)
          函数中变量的作用域(209)
          引用类型-数组(208)
          引用类型-字符串啊(207)
          引用类型-日期对象(206)
          引用类型-正则表达式(205)
          面向对象编程-类的声明和使用(204)
          面向对象编程-修饰符(203)
          面向对象编程-继承和重写(202)
          面向对象编程-接口(201)
          面向对象编程-命名空间(200)
          #11-Nuxt.js免费视频教程 开启SSR渲染 ( 共11集)
          NuxtJS课程介绍(199)
          Nuxt环境搭建和Hello World(198)
          Nuxt常用配置项(197)
          Nuxt的路由配置和参数传递(196)
          Nuxt的动态路由和参数校验(195)
          Nuxt的路由动画效果(194)
          Nuxt的默认模版和默认布局(193)
          Nuxt的错误页面和个性meta设置(192)
          asyncData方法获取数据(191)
          静态资源和打包(190)
          #12-CocosCreator 从基础到实战免费视频
          CocosCreator简介和HelloWorld(189)
          软件界面介绍和跳动的小球(188)
          Scene介绍和基本操作(187)
          玩家输入事件监听(186)
          Prefab和计时器(185)
          实战-游戏简介和项目分析(184)
          实战-UI界面布局(183)
          实战-主角的动作监听和跳动(182)
          实战-随机生成地刺(181)
          实战-点击生成地刺和移动(180)
          实战-碰撞检测(179)
          实战-倒计时和分数增加(178)
          实战-欢迎界面代码编写(177)
          实战-添加音效(176)
          实战-发布游戏(175)
          #13-挑战全栈 MongoDB基础视频教程 (共21集)
          认识和安装MongoDB(174)
          Mongo基本命令-1(173)
          Mongo基本命令-2(172)
          用js文件写mongo命令(171)
          批量插入的正确方法(170)
          修改：Update常见错误(169)
          修改：初识update修改器(168)
          修改：update数组修改器(167)
          修改：状态返回与安全(166)
          查询：find的不等修饰符(165)
          查询：find的多条件查询(164)
          查询：find的数组查询(163)
          查询：find的参数使用方法(162)
          查询：find如何在js文本中使用(161)
          索引:构造百万级数据(160)
          索引：索引入门(159)
          索引：复合索引(158)
          索引：全文索引(157)
          管理:用户的创建、删除与修改(156)
          管理：备份和还原(155)
          管理：图形界面管理（完结）(154)
          #14-挑战全栈 Koa2免费视频教程 (共13集)
          Koa开发环境搭建(153)
          async/await的使用方法(152)
          Get请求的接收(151)
          POST请求如何接收（1）(150)
          POST请求如何接收（2）(149)
          koa-bodyparser中间件(148)
          Koa2原生路由实现(147)
          Koa-router中间件（1）入门(146)
          Koa-router中间件（2）层级(145)
          Koa-router中间件（3）参数(144)
          Koa2中使用cookie(143)
          Koa2的模板初识（ejs）(142)
          koa-static静态资源中间件(141)
          #15-React免费视频教程-入门和组件 (共11集)
          React课程介绍(140)
          环境搭建和HelloWorld程序(139)
          初识JSX语法(138)
          进阶JSX语法(137)
          React组件：state成员(136)
          React组件：props和render成员(135)
          React组件：生命周期(134)
          React组件小实例-必做练习(133)
          React组件：this.props.children(132)
          React组件：props属性验证(131)
          React组件：获取真实DOM节点(130)
          #16-React免费视频教程-表单的应用 (共4集)
          表单的事件响应和bind复用(129)
          React表单name复用(128)
          React表单-可控组件(127)
          React表单-不可控组件(126)
          #17-React项目构建和路由 免费视频教程 (共10集)
          构建：create-react-app 快速脚手架(125)
          构建：generator-react-webpack(124)
          构建：webpack一步一步构建01(123)
          构建：webpack一步一步构建02(122)
          路由：Hello React路由(121)
          路由：NavLink中常用选项(120)
          路由：404设置和跳转设置(119)
          路由：通过路由传值的方法(118)
          路由：Router中的属性和路由模式(117)
          路由：prompt用法讲解(116)
          #18-Vue2.0视频教程-内部指令(共8集)
          走起我的Vue2.0(115)
          v-if v-else v-show 指令(114)
          v-for指令 ：解决模板循环问题(113)
          v-text & v-html(112)
          v-on：绑定事件监听器(111)
          v-model指令(110)
          v-bind 指令(109)
          其他内部指令(v-pre & v-cloak & v-once)(108)
          #19-【第二季】Vue2.0视频教程-全局API(共9集)
          Vue.directive 自定义指令(107)
          Vue.extend构造器的延伸(106)
          Vue.set全局操作(105)
          Vue的生命周期（钩子函数）(104)
          Template 制作模版(103)
          Component 初识组件(102)
          Component 组件props 属性设置(101)
          Component 父子组件关系(100)
          Component 标签(099)
          #20-【第三季】Vue2.0视频教程-选项（共6集）
          propsData Option 全局扩展的数据传递(098)
          computed Option 计算选项(097)
          Methods Option 方法选项(096)
          Watch 选项 监控数据(095)
          Extends Option 扩展选项(094)
          #21-【第四季】Vue2.0视频教程-实例和内置组件（共4集）
          实例入门-实例属性(093)
          实例方法(092)
          实例事件(091)
          内置组件 -slot讲解(090)
          #22-Vue-cli 免费视频教程(共3集)
          Vue-cli，开始吧骚年(089)
          Vue-cli项目结构讲解(088)
          解读Vue-cli的模板(087)
          #23-Vue-router免费视频教程(共11集)
          Vue-router入门(086)
          vue-router配置子路由(085)
          vue-router如何参数传递(084)
          单页面多路由区域操作(083)
          vue-router 利用url传递参数(082)
          vue-router 的重定向-redirect(081)
          alias别名的使用(080)
          路由的过渡动画(079)
          mode的设置和404页面的处理(078)
          路由中的钩子(077)
          编程式导航(076)
          #24-vuex免费视频教程(共6集)
          初出茅庐 来个小Demo(075)
          state访问状态对象(074)
          Mutations修改状态(073)
          getters计算过滤操作(072)
          actions异步修改状态(071)
          module模块组(070)
          #25- Vue实战视频-快餐店收银系统 (共11集)
          Mockplus把我们的想法画出来(069)
          Vue-cli搭建开发环境(068)
          搞定项目图标Iconfont(067)
          编写独立的侧边栏导航组件(066)
          开启Element封印(065)
          利用Element快速布局（1）(064)
          利用Element快速布局（2）(063)
          Axios从远程读取数据(062)
          订单模块制作 核心功能-1(061)
          订单模块制作 核心功能-2(060)
          项目打包和上线(059)
          #26-WEEX免费视频教程-从入门到放肆 (共17集)
          课程介绍(058)
          开发环境安装(1)(057)
          开发环境安装(2)(056)
          weex常用命令和热更新(055)
          Android Studio 开发设置
          weex和vue的爱恨情仇(054)
          自定义组件和Text组件
          Input组件和初识内建模块(053)
          Image和video组件(052)
          一起作个列表出来(051)
          从后端服务器上获取数据(050)
          作轮播图片效果(049)
          a组件和web组件(048)
          通用事件和动画(047)
          教会你自学weex(046)
          Navigator和webview模块(046)
          vue-router的使用(045)
          #27-Fabric.js 免费视频教程(共13集)
          初识简单而且强大的Fabric.js库(044)
          在Canvas上画简单的图形(043)
          在Canvas上插入图片并设置旋转属性(042)
          Fabric.js用路径画不规则图形(041)
          Fabric.js的动画设置(040)
          Fabric.js的图像过滤器(039)
          Fabric.js的颜色模式和相互转换(038)
          Fabric.js的渐变填充(037)
          Fabric.js的文本设置(036)
          Fabric.js的事件系统(035)
          Fabric.js的分组绘制（一）(034)
          Fabric.js的分组绘制（二）(033)
          Fabric.js的序列化和反序列化(032)
          #28-CSS3免费视频教程(共31集)
          嫁汉嫁汉穿衣吃饭(031)
          CSS3新特性简介和浏览器支持情况 (030)
          CSS3伪类选择器1(029)
          CSS3伪类选择器2结构伪类选择器(028)
          CSS3伪元素(027)
          CSS3用border-radius画圆形(026)
          CSS3画三角形和对话框(025)
          CSS3画菱形和平行四边形(024)
          画五角星和六角星(023)
          CSS3 画五角星和六角星(022)
          CSS3画心形和蛋形(021)
          CSS3画太极阴阳图(020)
          CSS3制作透明背景层(019)
          CSS3的颜色模式(1)(018)
          CSS3的颜色模式（2）-实例仿天猫商品展示效果(017)
          CSS3线性渐变(016)
          CSS3径向渐变 radial-gradient(015)
          CSS3重复性渐变(014)
          CSS3盒子阴影效果box-shadow(013)
          CSS3制作缓慢变长的方形（transition特效）(012)
          CSS3制作缓慢变长的方形（transition特效）(011)
          CSS3过渡的timing-function属性详解(010)
          CSS3仿天猫专题过渡效果实例(009)
          SS3仿天猫类别过渡效果制作(008)
          CSS3动画中的@keyframes关键帧讲解(007)
          CSS3动画animation复合属性讲解(006)
          CSS3动画综合实例制作-内容加载loading动画实现(005)
          CSS3 Loading动画效果实例2(004)
          CSS3制作发光字，立体字，苹果字体(003)
          CSS3 用text-overflow解决文字排版问题(002)
          CSS3 新的字体单位rem-大结局(001)
          还在不断录制中................
        </div>
      </swiper-slide>
    </swiper>
  </div>
</template>

<script>
import "swiper/dist/css/swiper.css";
import { swiper, swiperSlide } from "vue-awesome-swiper";
export default {
  data() {
    return {
      swiperOption: {
        direction: "vertical",
        slidesPerView: "auto",
        freeMode: true,
        mousewheel: true
      }
    };
  },
  components: { swiper, swiperSlide }
};
</script>

<style scoped>
.swiper {
  height: 300px;
  overflow: hidden;
}
.text {
  font-size: 18px !important;
  text-align: left;
  padding: 30px;
  height: auto;
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
}
</style>